sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    host: localhost
#    port: 3306
    host: 8.134.220.254
    port: 3305
    database: sky_take_out
    username: root
    password: '010466'
#    password: Qq7758258

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tGCckZz5YHFwCfv7Lr6
    access-key-secret: akJd3fEsfAPzA5634VHptTcxO0pYAy
    bucket-name: tsoyim-sky-itcase

  redis:
#    host: localhost
#    port: 6379
    host: 8.134.220.254
    port: 6380
    password: 123456
    database: 4

  wechat:
    appid: wx80045ee10c2cd31d
    secret: 8fe76c34a492620b6471eec4946c6a67


