sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Qq7758258

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tGCckZz5YHFwCfv7Lr6
    access-key-secret: akJd3fEsfAPzA5634VHptTcxO0pYAy
    bucket-name: tsoyim-sky-itcase

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 4


